### ISSUE TITLE
Překryv odnoží

### ISSUE THREAD

**Issue by martilad** [3DprintFIT/B171CW-Assignment#2]
Při generování některé z mých vloček se mi stane že se mi odnože překrývají. Je toto bráno jako chyba nebo je možno mít tento překryv u některých vloček? A nebo případně takovou vločku tisknout?

**Comment by hroncok** [comment]
Zadání překryvy neřeší, pokud vznikají proto, že odpovídají zadní, neřeš to. Pokud to nechceš tak tisknout, můžeš zkusit k „vytočovacímu“ úhlu přičíst nějakou konstantu, jestli to pomůže.

**Comment by martilad** [comment]
děkuji zkusím. Děje se to hlavně u vločky s hodně větvemi.

**Comment by hroncok** [comment]
to dává smysl :)
